In [95]:
import pandas as pd

df = pd.read_csv("/Users/maimunaz/Downloads/churn_prediction/data/raw/telco-customer-churn.csv")
print(df.head())
print(df.info())

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No
1                No             DSL            Yes  ...              Yes
2                No             DSL            Yes  ...               No
3  No phone service             DSL            Yes  ...              Yes
4                No     Fiber optic             No  ...               No

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes
1          No          No              No        One year               No
2          No          No              No  Month-to-month              Yes
3         Yes          No              No        One year               No
4          No          No              No  Month-to-month              Yes

               PaymentMethod MonthlyCharges  TotalCharges Churn
0           Electronic check          29.85         29.85    No
1               Mailed check          56.95        1889.5    No
2               Mailed check          53.85        108.15   Yes
3  Bank transfer (automatic)          42.30       1840.75    No
4           Electronic check          70.70        151.65   Yes

[5 rows x 21 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

In [96]:
print(df.columns)  # Shows all column names
print(df.shape) # shows num of rows and columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')
(7043, 21)

In [97]:
print(df.head().T)

                                 0             1               2  \
customerID              7590-VHVEG    5575-GNVDE      3668-QPYBK
gender                      Female          Male            Male
SeniorCitizen                    0             0               0
Partner                        Yes            No              No
Dependents                      No            No              No
tenure                           1            34               2
PhoneService                    No           Yes             Yes
MultipleLines     No phone service            No              No
InternetService                DSL           DSL             DSL
OnlineSecurity                  No           Yes             Yes
OnlineBackup                   Yes            No             Yes
DeviceProtection                No           Yes              No
TechSupport                     No            No              No
StreamingTV                     No            No              No
StreamingMovies                 No            No              No
Contract            Month-to-month      One year  Month-to-month
PaperlessBilling               Yes            No             Yes
PaymentMethod     Electronic check  Mailed check    Mailed check
MonthlyCharges               29.85         56.95           53.85
TotalCharges                 29.85        1889.5          108.15
Churn                           No            No             Yes

                                          3                 4
customerID                       7795-CFOCW        9237-HQITU
gender                                 Male            Female
SeniorCitizen                             0                 0
Partner                                  No                No
Dependents                               No                No
tenure                                   45                 2
PhoneService                             No               Yes
MultipleLines              No phone service                No
InternetService                         DSL       Fiber optic
OnlineSecurity                          Yes                No
OnlineBackup                             No                No
DeviceProtection                        Yes                No
TechSupport                             Yes                No
StreamingTV                              No                No
StreamingMovies                          No                No
Contract                           One year    Month-to-month
PaperlessBilling                         No               Yes
PaymentMethod     Bank transfer (automatic)  Electronic check
MonthlyCharges                         42.3              70.7
TotalCharges                        1840.75            151.65
Churn                                    No               Yes

In [98]:
print(df["TotalCharges"].dtype)
print(df["TotalCharges"].head(10))

object
0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
5      820.5
6     1949.4
7      301.9
8    3046.05
9    3487.95
Name: TotalCharges, dtype: object

In [99]:
print(df[~df["TotalCharges"].str.replace(".", "", regex=False).str.isnumeric()])

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
488   4472-LVYGI  Female              0     Yes        Yes       0
753   3115-CZMZD    Male              0      No        Yes       0
936   5709-LVOEQ  Female              0     Yes        Yes       0
1082  4367-NUYAO    Male              0     Yes        Yes       0
1340  1371-DWPAZ  Female              0     Yes        Yes       0
3331  7644-OMVMY    Male              0     Yes        Yes       0
3826  3213-VVOLG    Male              0     Yes        Yes       0
4380  2520-SGTTA  Female              0     Yes        Yes       0
5218  2923-ARZLG    Male              0     Yes        Yes       0
6670  4075-WKNIU  Female              0     Yes        Yes       0
6754  2775-SEFEE    Male              0      No        Yes       0

     PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
488            No  No phone service             DSL                  Yes  ...
753           Yes                No              No  No internet service  ...
936           Yes                No             DSL                  Yes  ...
1082          Yes               Yes              No  No internet service  ...
1340           No  No phone service             DSL                  Yes  ...
3331          Yes                No              No  No internet service  ...
3826          Yes               Yes              No  No internet service  ...
4380          Yes                No              No  No internet service  ...
5218          Yes                No              No  No internet service  ...
6670          Yes               Yes             DSL                   No  ...
6754          Yes               Yes             DSL                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
488                   Yes                  Yes                  Yes
753   No internet service  No internet service  No internet service
936                   Yes                   No                  Yes
1082  No internet service  No internet service  No internet service
1340                  Yes                  Yes                  Yes
3331  No internet service  No internet service  No internet service
3826  No internet service  No internet service  No internet service
4380  No internet service  No internet service  No internet service
5218  No internet service  No internet service  No internet service
6670                  Yes                  Yes                  Yes
6754                   No                  Yes                   No

          StreamingMovies  Contract PaperlessBilling  \
488                    No  Two year              Yes
753   No internet service  Two year               No
936                   Yes  Two year               No
1082  No internet service  Two year               No
1340                   No  Two year               No
3331  No internet service  Two year               No
3826  No internet service  Two year               No
4380  No internet service  Two year               No
5218  No internet service  One year              Yes
6670                   No  Two year               No
6754                   No  Two year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges Churn
488   Bank transfer (automatic)          52.55                  No
753                Mailed check          20.25                  No
936                Mailed check          80.85                  No
1082               Mailed check          25.75                  No
1340    Credit card (automatic)          56.05                  No
3331               Mailed check          19.85                  No
3826               Mailed check          25.35                  No
4380               Mailed check          20.00                  No
5218               Mailed check          19.70                  No
6670               Mailed check          73.35                  No
6754  Bank transfer (automatic)          61.90                  No

[11 rows x 21 columns]

In [100]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")  # Converts and sets errors to NaN

In [101]:
print(df["TotalCharges"].dtype)  # Should now be float64
print(df["TotalCharges"].isna().sum())  # Count how many NaNs we got

float64
11

In [102]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)
print(df["TotalCharges"].isna().sum()) # Count how many NaNs we got

0

In [103]:
print(df["MonthlyCharges"].dtype)
print(df["MonthlyCharges"].head(10))

float64
0     29.85
1     56.95
2     53.85
3     42.30
4     70.70
5     99.65
6     89.10
7     29.75
8    104.80
9     56.15
Name: MonthlyCharges, dtype: float64

In [104]:
print(df["tenure"].dtype)
print(df["tenure"].head(10))

int64
0     1
1    34
2     2
3    45
4     2
5     8
6    22
7    10
8    28
9    62
Name: tenure, dtype: int64

In [105]:
print(df["tenure"].dtype)
print(df["tenure"].head(10))

int64
0     1
1    34
2     2
3    45
4     2
5     8
6    22
7    10
8    28
9    62
Name: tenure, dtype: int64

In [106]:
print(df.isna().sum())  # See how many missing values per column

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [107]:
print(df.isna().sum())  # See how many missing values per column

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [108]:
for col in df.select_dtypes(include=["object"]).columns:
    print(col, df[col].unique())

customerID ['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']
gender ['Female' 'Male']
Partner ['Yes' 'No']
Dependents ['No' 'Yes']
PhoneService ['No' 'Yes']
MultipleLines ['No phone service' 'No' 'Yes']
InternetService ['DSL' 'Fiber optic' 'No']
OnlineSecurity ['No' 'Yes' 'No internet service']
OnlineBackup ['Yes' 'No' 'No internet service']
DeviceProtection ['No' 'Yes' 'No internet service']
TechSupport ['No' 'Yes' 'No internet service']
StreamingTV ['No' 'Yes' 'No internet service']
StreamingMovies ['No' 'Yes' 'No internet service']
Contract ['Month-to-month' 'One year' 'Two year']
PaperlessBilling ['Yes' 'No']
PaymentMethod ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn ['No' 'Yes']

In [109]:
# binary encoding for columns with only 2 unique values

df["gender"] = df["gender"].map({"Female": 0, "Male": 1})
df["Partner"] = df["Partner"].map({"No": 0, "Yes": 1})
df["Dependents"] = df["Dependents"].map({"No": 0, "Yes": 1})
df["PhoneService"] = df["PhoneService"].map({"No": 0, "Yes": 1})
df["PaperlessBilling"]= df["PaperlessBilling"].map({"No": 0, "Yes": 1})
df["Churn"] = df["Churn"].map({"No": 0, "Yes": 1})

In [110]:
# one hot encoding for columns with more than 2 unique values
df = pd.get_dummies(df, columns=["Contract", "InternetService", "PaymentMethod"], drop_first=True)

In [111]:
# handling "No phone service" & "No internet service" --> making then to No 

cols_to_clean = ["MultipleLines", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies"]
for col in cols_to_clean:
    df[col] = df[col].replace({"No phone service": "No", "No internet service": "No"})
    df[col] = df[col].map({"No": 0, "Yes": 1})

In [112]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,...,MonthlyCharges,TotalCharges,Churn,Contract_One year,Contract_Two year,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,7590-VHVEG,0,0,1,0,1,0,0,0,1,...,29.85,29.85,0,False,False,False,False,False,True,False
1,5575-GNVDE,1,0,0,0,34,1,0,1,0,...,56.95,1889.50,0,True,False,False,False,False,False,True
2,3668-QPYBK,1,0,0,0,2,1,0,1,1,...,53.85,108.15,1,False,False,False,False,False,False,True
3,7795-CFOCW,1,0,0,0,45,0,0,1,0,...,42.30,1840.75,0,True,False,False,False,False,False,False
4,9237-HQITU,0,0,0,0,2,1,0,0,0,...,70.70,151.65,1,False,False,True,False,False,True,False

In [114]:
df[["Contract_One year", "Contract_Two year",
    "InternetService_Fiber optic", "InternetService_No",
    "PaymentMethod_Credit card (automatic)", "PaymentMethod_Electronic check",
    "PaymentMethod_Mailed check"]] = df[["Contract_One year", "Contract_Two year",
                                         "InternetService_Fiber optic", "InternetService_No",
                                         "PaymentMethod_Credit card (automatic)", "PaymentMethod_Electronic check",
                                         "PaymentMethod_Mailed check"]].astype(int)

In [116]:
df.drop(columns=["customerID"], inplace=True)

In [117]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,MonthlyCharges,TotalCharges,Churn,Contract_One year,Contract_Two year,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,0,1,0,...,29.85,29.85,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,1,0,1,...,56.95,1889.50,0,1,0,0,0,0,0,1
2,1,0,0,0,2,1,0,1,1,0,...,53.85,108.15,1,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,1,0,1,...,42.30,1840.75,0,1,0,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,0,0,1,0,0,1,0

In [120]:
df.to_csv("/Users/maimunaz/Downloads/churn_prediction/data/processed/telco_cleaned.csv", index=False)